### ISSUE TITLE
B站似乎并不生效

### ISSUE THREAD

**Issue by Higurashi-kagome** [Pangu2020together/video-play-speed-extension#1]
如图 ：

![image](https://user-images.githubusercontent.com/51501079/84638239-47b84500-af29-11ea-8e85-e081b32887a4.png)

**Comment by Affirc60sec** [comment]
B站无法使用是因为突然多了个HVEC功能，在视频设置里禁止使用HVEC就可以了。

**Comment by Affirc60sec** [comment]
但你这个是2020年的评论不确定我的方法有没有效果（？

**Comment by Higurashi-kagome** [comment]
刚刚发现已经没有这个问题了，谢谢。 @Affirc60sec
